# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistName', models.CharField(max_length=200)),
                ('BIO', models.TextField()),
                ('Picture', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Details', models.TextField()),
                ('Logo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Display.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='Genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Display.Genre'),
            preserve_default=False,
        ),
    ]
