# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0003_auto_20170628_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_name', models.CharField(max_length=200)),
                ('Artist_request', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
