# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0004_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Artist_request',
            new_name='Artist',
        ),
    ]
